import type { StockItem } from '../types/stock';

export const INITIAL_ITEMS: StockItem[] = [
  {
    id: 'item-1',
    no: 1,
    name: 'แบล็ค',
    category: 'liquor',
    unit: 'ขวด',
    broughtForward: '',
    added: '',
    openFront: '',
    openBack: '',
    closeFront: '',
    closeBack: '',
    remark: '',
  },
  {
    id: 'item-2',
    no: 2,
    name: 'เรด',
    category: 'liquor',
    unit: 'ขวด',
    broughtForward: '',
    added: '',
    openFront: '',
    openBack: '',
    closeFront: '',
    closeBack: '',
    remark: '',
  },
  {
    id: 'item-3',
    no: 3,
    name: 'รีเจนซี่ แบน',
    category: 'liquor',
    unit: 'แบน',
    broughtForward: '',
    added: '',
    openFront: '',
    openBack: '',
    closeFront: '',
    closeBack: '',
    remark: '',
  },
  {
    id: 'item-4',
    no: 4,
    name: 'เมอริเดียน กลม',
    category: 'liquor',
    unit: 'กลม',
    broughtForward: '',
    added: '',
    openFront: '',
    openBack: '',
    closeFront: '',
    closeBack: '',
    remark: '',
  },
  {
    id: 'item-5',
    no: 5,
    name: 'เมอริเดียน แบน',
    category: 'liquor',
    unit: 'แบน',
    broughtForward: '',
    added: '',
    openFront: '',
    openBack: '',
    closeFront: '',
    closeBack: '',
    remark: '',
  },
  {
    id: 'item-6',
    no: 6,
    name: 'แสงโสม กลม',
    category: 'liquor',
    unit: 'กลม',
    broughtForward: '',
    added: '',
    openFront: '',
    openBack: '',
    closeFront: '',
    closeBack: '',
    remark: '',
  },
  {
    id: 'item-7',
    no: 7,
    name: 'แสงโสม แบน',
    category: 'liquor',
    unit: 'แบน',
    broughtForward: '',
    added: '',
    openFront: '',
    openBack: '',
    closeFront: '',
    closeBack: '',
    remark: '',
  },
  {
    id: 'item-8',
    no: 8,
    name: 'หงษ์ทอง กลม',
    category: 'liquor',
    unit: 'กลม',
    broughtForward: '',
    added: '',
    openFront: '',
    openBack: '',
    closeFront: '',
    closeBack: '',
    remark: '',
  },
  {
    id: 'item-9',
    no: 9,
    name: 'สิงห์',
    category: 'beer',
    unit: 'ขวด',
    broughtForward: '',
    added: '',
    openFront: '',
    openBack: '',
    closeFront: '',
    closeBack: '',
    remark: '',
  },
  {
    id: 'item-10',
    no: 10,
    name: 'ลีโอ',
    category: 'beer',
    unit: 'ขวด',
    broughtForward: '',
    added: '',
    openFront: '',
    openBack: '',
    closeFront: '',
    closeBack: '',
    remark: '',
  },
  {
    id: 'item-11',
    no: 11,
    name: 'สไปรท์',
    category: 'mixer',
    unit: 'กระป๋อง',
    broughtForward: '',
    added: '',
    openFront: '',
    openBack: '',
    closeFront: '',
    closeBack: '',
    remark: '',
  },
  {
    id: 'item-12',
    no: 12,
    name: 'โค้ก',
    category: 'mixer',
    unit: 'กระป๋อง',
    broughtForward: '',
    added: '',
    openFront: '',
    openBack: '',
    closeFront: '',
    closeBack: '',
    remark: '',
  },
  {
    id: 'item-13',
    no: 13,
    name: 'น้ำเปล่า',
    category: 'mixer',
    unit: 'ขวด',
    broughtForward: '',
    added: '',
    openFront: '',
    openBack: '',
    closeFront: '',
    closeBack: '',
    remark: '',
  },
  {
    id: 'item-14',
    no: 14,
    name: 'โซดา',
    category: 'mixer',
    unit: 'ขวด',
    broughtForward: '',
    added: '',
    openFront: '',
    openBack: '',
    closeFront: '',
    closeBack: '',
    remark: '',
  },
];

export const SAMPLE_MOCK_DATA: StockItem[] = [
  {
    id: 'item-1',
    no: 1,
    name: 'แบล็ค',
    category: 'liquor',
    unit: 'ขวด',
    broughtForward: 5,
    added: 3,
    openFront: 3,
    openBack: 5,
    closeFront: 2,
    closeBack: 4,
    remark: 'เบิกเพิ่มช่วง 2 ทุ่ม',
  },
  {
    id: 'item-2',
    no: 2,
    name: 'เรด',
    category: 'liquor',
    unit: 'ขวด',
    broughtForward: 4,
    added: 2,
    openFront: 2,
    openBack: 3,
    closeFront: 1,
    closeBack: 2,
    remark: 'แตก 1 ขวดหน้าร้าน',
  },
  {
    id: 'item-3',
    no: 3,
    name: 'รีเจนซี่ แบน',
    category: 'liquor',
    unit: 'แบน',
    broughtForward: 8,
    added: 12,
    openFront: 10,
    openBack: 10,
    closeFront: 4,
    closeBack: 7,
    remark: 'ขายดีมาก',
  },
  {
    id: 'item-4',
    no: 4,
    name: 'เมอริเดียน กลม',
    category: 'liquor',
    unit: 'กลม',
    broughtForward: 6,
    added: 0,
    openFront: 2,
    openBack: 4,
    closeFront: 1,
    closeBack: 3,
    remark: '',
  },
  {
    id: 'item-5',
    no: 5,
    name: 'เมอริเดียน แบน',
    category: 'liquor',
    unit: 'แบน',
    broughtForward: 4,
    added: 6,
    openFront: 4,
    openBack: 6,
    closeFront: 2,
    closeBack: 3,
    remark: '',
  },
  {
    id: 'item-6',
    no: 6,
    name: 'แสงโสม กลม',
    category: 'liquor',
    unit: 'กลม',
    broughtForward: 10,
    added: 5,
    openFront: 5,
    openBack: 10,
    closeFront: 2,
    closeBack: 6,
    remark: '',
  },
  {
    id: 'item-7',
    no: 7,
    name: 'แสงโสม แบน',
    category: 'liquor',
    unit: 'แบน',
    broughtForward: 7,
    added: 0,
    openFront: 3,
    openBack: 4,
    closeFront: 1,
    closeBack: 2,
    remark: '',
  },
  {
    id: 'item-8',
    no: 8,
    name: 'หงษ์ทอง กลม',
    category: 'liquor',
    unit: 'กลม',
    broughtForward: 12,
    added: 12,
    openFront: 8,
    openBack: 16,
    closeFront: 3,
    closeBack: 8,
    remark: 'โต๊ะ VIP สั่งยกลัง',
  },
  {
    id: 'item-9',
    no: 9,
    name: 'สิงห์',
    category: 'beer',
    unit: 'ขวด',
    broughtForward: 24,
    added: 48,
    openFront: 24,
    openBack: 48,
    closeFront: 8,
    closeBack: 20,
    remark: 'โปร 3 ขวด',
  },
  {
    id: 'item-10',
    no: 10,
    name: 'ลีโอ',
    category: 'beer',
    unit: 'ขวด',
    broughtForward: 36,
    added: 72,
    openFront: 30,
    openBack: 78,
    closeFront: 12,
    closeBack: 24,
    remark: 'ยอดนิยมอันดับ 1',
  },
  {
    id: 'item-11',
    no: 11,
    name: 'สไปรท์',
    category: 'mixer',
    unit: 'กระป๋อง',
    broughtForward: 15,
    added: 24,
    openFront: 12,
    openBack: 27,
    closeFront: 5,
    closeBack: 14,
    remark: '',
  },
  {
    id: 'item-12',
    no: 12,
    name: 'โค้ก',
    category: 'mixer',
    unit: 'กระป๋อง',
    broughtForward: 20,
    added: 48,
    openFront: 20,
    openBack: 48,
    closeFront: 6,
    closeBack: 18,
    remark: '',
  },
  {
    id: 'item-13',
    no: 13,
    name: 'น้ำเปล่า',
    category: 'mixer',
    unit: 'ขวด',
    broughtForward: 30,
    added: 60,
    openFront: 20,
    openBack: 70,
    closeFront: 10,
    closeBack: 35,
    remark: '',
  },
  {
    id: 'item-14',
    no: 14,
    name: 'โซดา',
    category: 'mixer',
    unit: 'ขวด',
    broughtForward: 40,
    added: 80,
    openFront: 35,
    openBack: 85,
    closeFront: 15,
    closeBack: 40,
    remark: '',
  },
];
